version: 2
jobs:
    build:
        working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
        docker:
            - image: golang:1.9
        steps:
            - checkout
            - run:
                name: run test
                command: |
                    go test -v ./...
